### Libraries, data import & EDA

In [1]:
!pip install XGboost
!pip install sweetviz
!pip install sklearn
!pip install category_encoders

Requirement already satisfied: XGboost in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from XGboost) (2.4.4)
Requirement already satisfied: scipy in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from XGboost) (1.17.1)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: sweetviz in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from sweetviz) (3.0.3)
Requirement already satisfied: numpy>=1.16.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from sweetviz) (2.4.4)
Requirement already satisfied: matplotlib>=3.1.3 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from sweetviz) (3.10.9)
Requirement already satisfied: tqdm>=4.43.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from sweetviz) (4.67.3)
Requirement already satisfied: scipy>=1.3.2 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from sweetviz) (1.17.1)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\prchandr\appdata\roaming\python\python312\site-packages (from matplotlib>=3.1.3->sweetviz) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\prchandr\appdata\roaming\python\python312\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.2)
Requirement already satisfied: colorama in c:\users\prchandr\appdata\roaming\python\python312\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\prchandr\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Requirement already satisfied: category_encoders in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from category_encoders) (2.4.4)
Requirement already satisfied: pandas>=1.0.5 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from category_encoders) (3.0.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from category_encoders) (1.17.1)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\prchandr\appdata\roaming\python\python312\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.3.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\prchandr\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\prchandr\appdata\roaming\python\python312\site-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in c:\users\prchandr\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# importing libraries
import numpy as np
import pandas as pd
from scipy.stats import boxcox
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report
import sweetviz as sv
from sklearn.cluster import KMeans
import category_encoders as ce
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score

c:\Users\prchandr\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# importing the data
adult = pd.read_csv("adult.csv")
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [4]:
# quick eda with sweetviz
report = sv.analyze(adult)
report.show_html("sweetviz_report.html")

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:01 -> (00:00 left)

Report sweetviz_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

### Model agnostic data preprocessing & train/test split for reuse in all cells

In [5]:
# replace ? with np.nan
adult = adult.replace("?", np.nan)
adult.head()

# convert target variable to binary
adult["income"] = adult["income"].apply(lambda x: 1 if x == ">50K" else 0)

# convert gender to 0/1
if "gender" in adult.columns:
    adult["gender"] = adult["gender"].apply(lambda x: 1 if x == "Male" else 0)  
    
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,1,0,0,40,United-States,0
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,1,0,0,50,United-States,0
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,1,0,0,40,United-States,1
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,1,7688,0,40,United-States,1
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,0,0,0,30,United-States,0

In [6]:
# check for na values
adult.isna().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [7]:
# drop na values
adult = adult.dropna() # dropping nulls
adult.isna().sum() # checking for no nulls

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [8]:
# shuffle the data
adult = adult.sample(frac = 1, random_state = 42).reset_index(drop = True) # added a random seed to make consistent outputs
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,19,Self-emp-not-inc,30800,10th,6,Married-spouse-absent,Adm-clerical,Unmarried,Amer-Indian-Eskimo,0,0,0,40,United-States,0
1,45,Private,26781,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,Amer-Indian-Eskimo,1,0,0,40,United-States,0
2,47,Private,431515,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,1,0,0,40,United-States,1
3,23,Private,45713,Some-college,10,Never-married,Craft-repair,Other-relative,White,1,0,0,40,United-States,0
4,53,Local-gov,175897,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,1,0,0,40,United-States,0

In [9]:
# define features and target
X = adult.drop("income", axis=1)
y = adult["income"]

# define categorical and numerical columns from X
cat_cols = X.select_dtypes(include=["object"]).columns.tolist()
num_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

ordinal_cols = ["education"]
nominal_cols = [col for col in cat_cols if col not in ordinal_cols]

print("Numerical:", num_cols)
print("Ordinal:", ordinal_cols)
print("Nominal:", nominal_cols)

# train/test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,              # NOT adult
    y,              # target
    test_size=0.2,
    stratify=y,
    random_state=42
)

Numerical: ['age', 'fnlwgt', 'educational-num', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week']
Ordinal: ['education']
Nominal: ['workclass', 'marital-status', 'occupation', 'relationship', 'race', 'native-country']

C:\Users\prchandr\AppData\Local\Temp\1\ipykernel_40772\3762481971.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include=["object"]).columns.tolist()

# Data Processing Pipelines

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

education_order = [[
    'Preschool',
    '1st-4th',
    '5th-6th',
    '7th-8th',
    '9th',
    '10th',
    '11th',
    '12th',
    'HS-grad',
    'Some-college',
    'Assoc-voc',
    'Assoc-acdm',
    'Bachelors',
    'Masters',
    'Prof-school',
    'Doctorate'
]]

numeric_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

ordinal_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder(categories=education_order))
])

nominal_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_pipeline, num_cols),
        ('ord', ordinal_pipeline, ordinal_cols),
        ('cat', nominal_pipeline, nominal_cols)
    ]
)

# applying preprocessors to my train/test split
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# Constructing my neural networks

In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# get number of input features after preprocessing
input_shape = X_train_processed.shape[1]

In [12]:
inputs = keras.Input(shape=(input_shape,))

x = layers.Dense(64, activation='relu')(inputs)
x = layers.Dense(32, activation='relu')(x)
x = layers.Dense(16, activation='relu')(x)

outputs = layers.Dense(1, activation='sigmoid')(x)

model = keras.Model(
    inputs=inputs,
    outputs=outputs,
    name="adult_income_neuralnet"
)

model.summary()

Model: "adult_income_neuralnet"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         5,696 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,321 (32.50 KB)

 Trainable params: 8,321 (32.50 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.compile(
    loss=keras.losses.BinaryCrossentropy(),
    optimizer=keras.optimizers.Adam(),
    metrics=['accuracy']
)

history = model.fit(
    X_train_processed,
    y_train,
    batch_size=64,
    epochs=20,
    validation_split=0.1
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.
Epoch 1/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.8392 - loss: 0.3433 - val_accuracy: 0.8499 - val_loss: 0.3253
Epoch 2/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.8521 - loss: 0.3195 - val_accuracy: 0.8568 - val_loss: 0.3079
Epoch 3/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.8535 - loss: 0.3153 - val_accuracy: 0.8546 - val_loss: 0.3056
Epoch 4/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8548 - loss: 0.3134 - val_accuracy: 0.8543 - val_loss: 0.3047
Epoch 5/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8557 - loss: 0.3107 - val_accuracy: 0.8566 - val_loss: 0.3072
Epoch 6/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8564 - loss: 0.3088 - val_accuracy: 0.8538 - val_loss: 0.3046
Epoch 7/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8562 - loss: 0.3065 - val_accuracy: 0.8579 - val_loss: 0.3056
Epoch 8/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8583 - loss: 0.3039 - val_accuracy: 0.8566 - val_loss: 0.3050
Epoch 9/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8596 - loss: 0.3020 - val_accuracy: 0.8554 - val_loss: 0.3084
Epoch 10/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8591 - loss: 0.2998 - val_accuracy: 0.8568 - val_loss: 0.3049
Epoch 11/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8600 - loss: 0.2988 - val_accuracy: 0.8577 - val_loss: 0.3034
Epoch 12/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8605 - loss: 0.2966 - val_accuracy: 0.8538 - val_loss: 0.3075
Epoch 13/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8618 - loss: 0.2956 - val_accuracy: 0.8560 - val_loss: 0.3067
Epoch 14/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8621 - loss: 0.2942 - val_accuracy: 0.8571 - val_loss: 0.3071
Epoch 15/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8620 - loss: 0.2923 - val_accuracy: 0.8593 - val_loss: 0.3061
Epoch 16/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8641 - loss: 0.2905 - val_accuracy: 0.8516 - val_loss: 0.3162
Epoch 17/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8655 - loss: 0.2887 - val_accuracy: 0.8541 - val_loss: 0.3148
Epoch 18/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8658 - loss: 0.2878 - val_accuracy: 0.8524 - val_loss: 0.3132
Epoch 19/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8662 - loss: 0.2869 - val_accuracy: 0.8557 - val_loss: 0.3074
Epoch 20/20
509/509 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8664 - loss: 0.2847 - val_accuracy: 0.8568 - val_loss: 0.3126

# Training and Validation Accuracy